#!/usr/bin/env python3
"""Write Tier A/B manifest with official IRD hub PDF URLs (Income Tax publications folder)."""

from __future__ import annotations

import csv
from pathlib import Path

BASE = "http://www.ird.gov.lk/en/publications/Acts_Income%20Tax_2017"

ROWS: list[dict[str, str]] = [
    {
        "source_doc_id": "ird-ira-2017",
        "title": "Inland Revenue Act No. 24 of 2017 (English)",
        "source_url": f"{BASE}/IR_Act_No_24_2017_E.pdf",
        "doc_type": "pdf",
        "instrument_type": "base_act",
        "tier": "A",
        "publication_date": "2017-10-24",
        "effective_start_date": "2018-04-01",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IR_Act_No_24_2017_E.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "IRD Income Tax hub publications link.",
    },
    {
        "source_doc_id": "ird-ira-amend-10-2021",
        "title": "Inland Revenue Amendment Act No. 10 of 2021 (English)",
        "source_url": f"{BASE}/IR_Act_No._10_2021_E.pdf",
        "doc_type": "pdf",
        "instrument_type": "amendment_act",
        "tier": "A",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IR_Act_No._10_2021_E.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "Verify effective dates from gazette or PDF cover.",
    },
    {
        "source_doc_id": "ird-ira-amend-45-2022",
        "title": "Inland Revenue Amendment Act No. 45 of 2022 (English)",
        "source_url": f"{BASE}/IR_Act_No._45_2022_E.pdf",
        "doc_type": "pdf",
        "instrument_type": "amendment_act",
        "tier": "A",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IR_Act_No._45_2022_E.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "",
    },
    {
        "source_doc_id": "ird-ira-amend-04-2023",
        "title": "Inland Revenue Amendment Act No. 04 of 2023 (English)",
        "source_url": f"{BASE}/IR_Act_No._04_2023_E.pdf",
        "doc_type": "pdf",
        "instrument_type": "amendment_act",
        "tier": "A",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IR_Act_No._04_2023_E.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "",
    },
    {
        "source_doc_id": "ird-ira-amend-14-2023",
        "title": "Inland Revenue Amendment Act No. 14 of 2023 (English)",
        "source_url": f"{BASE}/IR_Act_No14_2023_E.pdf",
        "doc_type": "pdf",
        "instrument_type": "amendment_act",
        "tier": "A",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IR_Act_No14_2023_E.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "",
    },
    {
        "source_doc_id": "ird-ira-amend-02-2025",
        "title": "Inland Revenue Amendment Act No. 02 of 2025 (English)",
        "source_url": f"{BASE}/IR_Act_No_02-2025_E.pdf",
        "doc_type": "pdf",
        "instrument_type": "amendment_act",
        "tier": "A",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IR_Act_No_02-2025_E.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "",
    },
    {
        "source_doc_id": "ird-ira-consolidated-2025",
        "title": "Inland Revenue Act consolidated changes (English; as per IRD file name)",
        "source_url": f"{BASE}/IRA_Cons_Act_-_2025_Changes.pdf",
        "doc_type": "pdf",
        "instrument_type": "consolidated",
        "tier": "A",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "false",
        "authority_weight": "1.00",
        "language": "en",
        "file_name": "IRA_Cons_Act_-_2025_Changes.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "Confirm as-of date printed on PDF cover; update publication_date when verified.",
    },
    {
        "source_doc_id": "ird-ira-guide-draft",
        "title": "Guide to Inland Revenue Act (English)",
        "source_url": f"{BASE}/Guide%20to%20Inland%20Revenue%20Act.pdf",
        "doc_type": "pdf",
        "instrument_type": "guide",
        "tier": "B",
        "publication_date": "",
        "effective_start_date": "",
        "effective_end_date": "",
        "version_label": "ird-hub-acts-income-tax-2017",
        "supersedes_source_doc_id": "",
        "is_draft": "true",
        "authority_weight": "0.60",
        "language": "en",
        "file_name": "Guide to Inland Revenue Act.pdf",
        "sha256": "",
        "ingested_at_utc": "",
        "ingested_by": "agent-step2",
        "notes": "Tier B interpretive; confirm draft status on IRD site.",
    },
]

FIELDNAMES = [
    "source_doc_id",
    "title",
    "source_url",
    "doc_type",
    "instrument_type",
    "tier",
    "publication_date",
    "effective_start_date",
    "effective_end_date",
    "version_label",
    "supersedes_source_doc_id",
    "is_draft",
    "authority_weight",
    "language",
    "file_name",
    "sha256",
    "ingested_at_utc",
    "ingested_by",
    "notes",
]


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    raw = repo / "data" / "raw" / "ird"
    raw.mkdir(parents=True, exist_ok=True)
    out = raw / "source_manifest.csv"
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDNAMES)
        w.writeheader()
        w.writerows(ROWS)
    print(out)


if __name__ == "__main__":
    main()
