import type { FinancialProfile } from "@/features/personalized-recommendation/types";

import type {
  BizRow,
  DivRow,
  EmployerRow,
  FdRow,
  PropRow,
  TaxReturnDetail,
} from "./types";

export const blankEmployer = (): EmployerRow => ({
  name: "",
  tin: "",
  role: "",
  from: "",
  to: "",
  current: "yes",
  gross: "",
  apit: "",
  epf: "",
  etf: "",
  bonus: "",
  allowances: "",
  noncash: "",
  overtime: "",
});

export const blankFd = (): FdRow => ({
  bank: "",
  accNo: "",
  maturity: "",
  principal: "",
  interest: "",
  wht: "",
  type: "fd",
});

export const blankDiv = (): DivRow => ({
  company: "",
  shares: "",
  dps: "",
  total: "",
  wht: "",
  resident: "yes",
});

export const blankBiz = (): BizRow => ({
  name: "",
  regNo: "",
  type: "sole",
  nature: "",
  start: "",
  revenue: "",
  cogs: "",
  wages: "",
  rent: "",
  utilities: "",
  depreciation: "",
  professional: "",
  advertising: "",
  other: "",
});

export const blankProp = (): PropRow => ({
  addr: "",
  type: "residential",
  usage: "rented",
  months: "12",
  rent: "",
  gross: "",
  joint: "no",
  share: "100",
  maintenance: "",
  insurance: "",
  mortgage: "",
  mgmt: "",
  other: "",
});

function provinceFromDistrict(district?: string): string {
  const map: Record<string, string> = {
    Colombo: "western",
    Gampaha: "western",
    Kalutara: "western",
    Kandy: "central",
    Matale: "central",
    "Nuwara Eliya": "central",
    Galle: "southern",
    Matara: "southern",
    Hambantota: "southern",
    Jaffna: "northern",
    Kilinochchi: "northern",
    Mannar: "northern",
    Mullaitivu: "northern",
    Vavuniya: "northern",
    Batticaloa: "eastern",
    Ampara: "eastern",
    Trincomalee: "eastern",
    Kurunegala: "north-western",
    Puttalam: "north-western",
    Anuradhapura: "north-central",
    Polonnaruwa: "north-central",
    Badulla: "uva",
    Monaragala: "uva",
    Ratnapura: "sabaragamuwa",
    Kegalle: "sabaragamuwa",
  };
  return map[district ?? ""] ?? "western";
}

export function createDefaultTaxReturnDetail(profile?: FinancialProfile): TaxReturnDetail {
  const fullName = profile?.full_name ?? "Kasun Perera";
  const preferredName = fullName.split(/\s+/)[0] ?? "Kasun";
  const taxYear = profile?.tax_year?.includes("-")
    ? profile.tax_year
    : profile?.tax_year
      ? `${profile.tax_year}-${Number(profile.tax_year) + 1}`
      : "2024-2025";
  const district = profile?.district ?? "Colombo";
  const grossAnnual = profile?.gross_monthly_income
    ? String(Number(profile.gross_monthly_income) * 12)
    : "1800000";
  const epfAnnual = profile?.epf_balance
    ? String(Math.min(Number(profile.epf_balance), Number(grossAnnual) * 0.08))
    : "162000";
  const lifePremium = profile?.life_insurance_premium_annual ?? "72000";
  const homeLoanInterest = profile?.home_loan_interest_annual ?? "";
  const donations = profile?.donations_annual ?? "";

  return {
    section1: {
      fullName,
      preferredName,
      nic: "922345678V",
      tin: "134567890",
      dob: profile?.date_of_birth ?? "1992-08-14",
      gender: profile?.gender ?? "male",
      nationality: "lk",
      residency: profile?.residency_status === "non_resident" ? "non-resident" : "resident",
      filingBasis: "individual",
      marital: profile?.marital_status ?? "single",
      dependants: profile?.dependents != null ? String(profile.dependents) : "0",
      taxYear,
      email: "kasun@example.lk",
      phone: "+94 77 123 4567",
      altPhone: "",
      addr1: "42A, Flower Road",
      addr2: "",
      city: "Colombo 03",
      district,
      province: provinceFromDistrict(district),
      postal: "00300",
      spouseName: "",
      spouseNic: "",
      spouseTin: "",
      spouseEmployer: "",
      agentName: "",
      agentTin: "",
      agentFirm: "",
      agentPhone: "",
      agentEmail: "",
      passport: "",
      hasSpouse: profile?.marital_status === "married",
      hasAgent: false,
    },
    section2: {
      employers: [
        {
          name: "ABC Pvt Ltd",
          tin: "123456789",
          role: "Software Engineer",
          from: "2021-01-01",
          to: "",
          current: "yes",
          gross: grossAnnual,
          apit: "108000",
          epf: epfAnnual,
          etf: "54000",
          bonus: profile?.annual_bonus_lkr ?? "150000",
          allowances: "60000",
          noncash: "0",
          overtime: "0",
        },
      ],
      hasDirector: false,
      directorFees: "",
      companyName: "",
      directorTin: "",
      hasGratuity: false,
      gratuityAmount: "",
      gratuityYears: "",
      gratuityType: "",
      hasSeverance: false,
      severanceAmount: "",
      severanceReason: "",
      hasCommission: false,
      commissionAmount: "",
      commissionPayer: "",
      hasPension: false,
      pensionAmount: "",
      pensionPayer: "",
      pensionType: "",
      hasGifts: false,
      giftAmount: "",
      giftDescription: "",
    },
    section3: {
      fds: [
        {
          bank: "Bank of Ceylon",
          accNo: "BOC-FD-001234",
          maturity: "2025-06-30",
          principal: "500000",
          interest: "87500",
          wht: "4375",
          type: "fd",
        },
      ],
      divs: [blankDiv()],
      hasSavings: true,
      savingsInterest: "8750",
      savingsWht: "437",
      hasGovSec: false,
      govTbill: "",
      govTbond: "",
      govInterest: "",
      govWht: "",
      hasUnitTrust: false,
      unitTrustFund: "",
      unitTrustDistribution: "",
      unitTrustWht: "",
      hasCSE: false,
      cseProceeds: "",
      cseCost: "",
      cseGain: "",
      hasREIT: false,
      reitFund: "",
      reitIncome: "",
    },
    section4: {
      businesses: [blankBiz()],
      hasFreelance: true,
      freelancePlatform: "upwork",
      freelanceCurrency: "usd",
      freelanceRevenue: "62500",
      freelanceRate: "320",
      freelanceLkr: "20000000",
      freelanceExpenses: "5000",
      freelanceCommissions: "6250",
      hasAgri: false,
      agriCrop: "",
      agriRevenue: "",
      agriExpenses: "",
      hasProfessional: false,
      professionalPractice: "",
      professionalRevenue: "",
      professionalExpenses: "",
    },
    section5: {
      properties: [
        {
          addr: "42A, Flower Road, Colombo 03",
          type: "residential",
          usage: "rented",
          months: "12",
          rent: "35000",
          gross: "420000",
          joint: "no",
          share: "100",
          maintenance: "21000",
          insurance: "",
          mortgage: "",
          mgmt: "",
          other: "",
        },
      ],
      hasDisposal: false,
      disposalAddr: "",
      disposalAcquired: "",
      disposalDisposed: "",
      disposalCost: "",
      disposalProceeds: "",
      disposalExpenses: "",
      hasLand: false,
      landAddr: "",
      landType: "",
      landRevenue: "",
    },
    section6: {
      hasLife: true,
      lifePremium,
      lifeInsurer: "AIA Life Sri Lanka",
      lifePolicy: "AIA-LK-20181234",
      hasMedical: profile?.health_insurance ?? false,
      medicalPremium: "",
      medicalInsurer: "",
      hasCharitable: Number(donations) > 0,
      charitablePresident: "",
      charitableApproved: donations || "",
      charitableReligious: "",
      charitableOther: "",
      hasEducation: false,
      educationSchool: "",
      educationFees: "",
      educationChildren: "1",
      hasPension: false,
      pensionFund: "",
      pensionType: "",
      pensionAmount: "",
      hasMortgage: Number(homeLoanInterest) > 0,
      mortgageBank: "",
      mortgageAccount: "",
      mortgageInterest: homeLoanInterest,
      hasRD: false,
      rdAmount: "",
      rdDescription: "",
      hasDisability: false,
      disabilityCategory: "",
      disabilityAmount: "",
    },
    section7: {
      hasForEmp: false,
      forEmpEmployer: "",
      forEmpCountry: "",
      forEmpCurrency: "usd",
      forEmpFgross: "",
      forEmpRate: "",
      forEmpLkr: "",
      forEmpFtax: "",
      forEmpDta: "unsure",
      hasForBiz: false,
      forBizDescription: "",
      forBizCountry: "",
      forBizRevenue: "",
      forBizFtax: "",
      hasForDiv: false,
      forDivCompany: "",
      forDivCountry: "",
      forDivTotal: "",
      forDivFtax: "",
      hasForProp: false,
      forPropCountry: "",
      forPropAddr: "",
      forPropType: "",
      forPropRental: "",
      forPropFtax: "",
      hasDTA: false,
      dtaCountry: "",
      dtaFtaxPaid: "",
      dtaCreditClaimed: "",
    },
    section8: {
      agreed: false,
    },
  };
}
