/** IRA Sections 5–8 income field catalog owned by this engine UI.
 *  Field labels and citations follow the Inland Revenue Act No. 24 of 2017.
 */

export type IncomeCatalogTreatment =
  | "include"
  | "exempt"
  | "final_withholding"
  | "deduct";

export type IncomeCatalogField = {
  component_id: string;
  display_name: string;
  sort_order: number;
  default_treatment: IncomeCatalogTreatment;
  section: string;
  paragraph?: string | null;
  reason_short?: string | null;
  confidence_reason?: string | null;
  legal_confidence: string;
  source_quote?: string | null;
  ui_group?: string | null;
};

export type IncomeCatalogCard = {
  card_id: string;
  display_name: string;
  sort_order: number;
  section: string;
  fields: IncomeCatalogField[];
};

export const INCOME_CATALOG_BADGE = "IRA Act 24/2017";

export const INCOME_CATALOG_CARDS: IncomeCatalogCard[] = [
  {
    card_id: "employment",
    display_name: "Employment Income",
    sort_order: 10,
    section: "5",
    fields: [
      {
        component_id: "emp_salary",
        display_name: "Salary",
        sort_order: 10,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Salary is included in calculating gains and profits from employment.",
        confidence_reason: "Directly listed in Section 5(2)(a) as salary.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_wages",
        display_name: "Wages",
        sort_order: 20,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Wages are included in calculating gains and profits from employment.",
        confidence_reason: "Directly listed in Section 5(2)(a) as wages.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_overtime",
        display_name: "Overtime",
        sort_order: 30,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Overtime pay is included in employment income.",
        confidence_reason: "Directly listed in Section 5(2)(a) as overtime pay.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_bonus",
        display_name: "Bonus",
        sort_order: 40,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Bonuses are included in calculating gains and profits from employment.",
        confidence_reason: "Directly listed in Section 5(2)(a) as bonuses.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_commission",
        display_name: "Commission",
        sort_order: 50,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Commissions are included in employment income.",
        confidence_reason: "Directly listed in Section 5(2)(a) as commissions.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_pension",
        display_name: "Pension",
        sort_order: 60,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Pensions are included in calculating gains and profits from employment.",
        confidence_reason: "Directly listed in Section 5(2)(a) as pensions.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_gratuity",
        display_name: "Gratuity",
        sort_order: 70,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Gratuities are included in employment income.",
        confidence_reason: "Directly listed in Section 5(2)(a) as gratuities.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_leave_pay",
        display_name: "Leave Pay",
        sort_order: 80,
        default_treatment: "include",
        section: "5",
        paragraph: "2(a)",
        reason_short: "Leave pay is included in calculating gains and profits from employment.",
        confidence_reason: "Directly listed in Section 5(2)(a) as leave pay.",
        legal_confidence: "high",
        source_quote: "payments of salary, wages, leave pay, overtime pay, fees, pensions, commissions, gratuities, bonuses and other similar payments;",
      },
      {
        component_id: "emp_housing_allowance",
        display_name: "Housing Allowance",
        sort_order: 90,
        default_treatment: "include",
        section: "5",
        paragraph: "2(b)",
        reason_short: "Personal allowances, including rent/housing allowance, are included in employment income.",
        confidence_reason: "Section 5(2)(b) includes personal allowance for rent/housing.",
        legal_confidence: "high",
        source_quote: "payments of personal allowance, including any cost of living, subsistence, rent, entertainment or travel allowance;",
      },
      {
        component_id: "emp_travel_allowance",
        display_name: "Travel Allowance",
        sort_order: 100,
        default_treatment: "include",
        section: "5",
        paragraph: "2(b)",
        reason_short: "Travel allowance is included as a personal allowance from employment.",
        confidence_reason: "Directly listed in Section 5(2)(b) as travel allowance.",
        legal_confidence: "high",
        source_quote: "payments of personal allowance, including any cost of living, subsistence, rent, entertainment or travel allowance;",
      },
      {
        component_id: "emp_cost_of_living_allowance",
        display_name: "Cost of Living Allowance",
        sort_order: 110,
        default_treatment: "include",
        section: "5",
        paragraph: "2(b)",
        reason_short: "Cost of living allowance is included in employment income.",
        confidence_reason: "Directly listed in Section 5(2)(b) as cost of living allowance.",
        legal_confidence: "high",
        source_quote: "payments of personal allowance, including any cost of living, subsistence, rent, entertainment or travel allowance;",
      },
      {
        component_id: "emp_entertainment_allowance",
        display_name: "Entertainment Allowance",
        sort_order: 120,
        default_treatment: "include",
        section: "5",
        paragraph: "2(b)",
        reason_short: "Entertainment allowance is included as a personal allowance from employment.",
        confidence_reason: "Directly listed in Section 5(2)(b) as entertainment allowance.",
        legal_confidence: "high",
        source_quote: "payments of personal allowance, including any cost of living, subsistence, rent, entertainment or travel allowance;",
      },
      {
        component_id: "emp_medical_benefits",
        display_name: "Medical Benefits",
        sort_order: 130,
        default_treatment: "exempt",
        section: "5",
        paragraph: "3(c)",
        reason_short: "Equal-terms medical/dental/health insurance benefits are excluded from employment income when Sec 5(3)(c) conditions are met.",
        confidence_reason: "Section 5(3)(c) excludes equal-terms dental/medical/health insurance reimbursements.",
        legal_confidence: "high",
        source_quote: "a discharge or reimbursement of the person's dental, medical or health insurance expenses where the benefit is available to all full-time employees on equal terms;",
      },
      {
        component_id: "emp_employer_retirement_contributions",
        display_name: "Employer Retirement Contributions",
        sort_order: 140,
        default_treatment: "exempt",
        section: "5",
        paragraph: "3(f)",
        reason_short: "CG-approved employer retirement contributions are excluded from employment income under Sec 5(3)(f).",
        confidence_reason: "Section 5(3)(f) excludes approved employer contributions to pension/provident/savings funds.",
        legal_confidence: "high",
        source_quote: "subject to conditions as may be specified by the Commissioner-General, contributions made by an employer to an employee's account with a pension, provident or savings fund or savings society approved by the Commissioner - General.",
      },
      {
        component_id: "emp_employee_share_scheme",
        display_name: "Employee Share Scheme",
        sort_order: 150,
        default_treatment: "include",
        section: "5",
        paragraph: "2(j)",
        reason_short: "Market value of shares allotted under an employee share scheme (net of employee contribution) is included.",
        confidence_reason: "Section 5(2)(j) includes market value of shares allotted under an employee share scheme.",
        legal_confidence: "high",
        source_quote: "the market value of shares at the time allotted under an employee share scheme, including shares allotted as a result of the exercise of an option or right to acquire the shares, reduced by the employee's contribution for the shares.",
      },
      {
        component_id: "emp_gifts",
        display_name: "Gifts",
        sort_order: 160,
        default_treatment: "include",
        section: "5",
        paragraph: "2(i)",
        reason_short: "Gifts received in respect of employment are included in employment income.",
        confidence_reason: "Section 5(2)(i) includes gifts received in respect of the employment.",
        legal_confidence: "high",
        source_quote: "other payments, including gifts received in respect of the employment; and",
      },
      {
        component_id: "emp_other_employment_benefits",
        display_name: "Other Employment Benefits",
        sort_order: 170,
        default_treatment: "include",
        section: "5",
        paragraph: "2(h)",
        reason_short: "Fair market value of employment benefits and other similar payments are included unless an exclusion in Sec 5(3) applies.",
        confidence_reason: "Section 5(2)(h)/(i) cover FMV benefits and other payments; classification of atypical benefits may need judgment.",
        legal_confidence: "medium",
        source_quote: "the fair market value of benefits received or derived by virtue of the employment by an individual or an associate person of the individual;",
      },
      {
        component_id: "emp_final_withholding",
        display_name: "Final Withholding / Exempt Amounts",
        sort_order: 180,
        default_treatment: "final_withholding",
        section: "5",
        paragraph: "3(a)",
        reason_short: "Exempt amounts and final withholding payments are excluded from employment income.",
        confidence_reason: "Section 5(3)(a) excludes exempt amounts and final withholding payments.",
        legal_confidence: "high",
        source_quote: "(3) In calculating an individual's gains and profits from an employment for a year of assessment the following shall be excluded:- (a) exempt amounts and final withholding payments;",
      },
    ],
  },
  {
    card_id: "business",
    display_name: "Business Income",
    sort_order: 15,
    section: "6",
    fields: [
      {
        component_id: "biz_net_profits",
        display_name: "Net Assessable Business Profits",
        sort_order: 10,
        default_treatment: "include",
        section: "6",
        reason_short: "Enter net profits after allowable expenses when you already know the assessable amount.",
        confidence_reason: "Sec 6 — assessable income from a business is the profits computed under the Act.",
        legal_confidence: "high",
        source_quote: "6. Business income. The assessable income from a business, profession or vocation for a year of assessment shall be the profits of the business computed in accordance with this Act and included in calculating assessable income.",
        ui_group: "net",
      },
      {
        component_id: "biz_gross",
        display_name: "Gross Business Receipts",
        sort_order: 20,
        default_treatment: "include",
        section: "6",
        reason_short: "Total business receipts before allowable expenses and capital allowances.",
        confidence_reason: "Sec 6 — business profits are computed from business income under the Act.",
        legal_confidence: "high",
        source_quote: "6. Business income. The assessable income from a business, profession or vocation for a year of assessment shall be the profits of the business computed in accordance with this Act and included in calculating assessable income.",
        ui_group: "breakdown",
      },
      {
        component_id: "biz_deductions",
        display_name: "Allowable Business Expenses",
        sort_order: 30,
        default_treatment: "deduct",
        section: "11",
        paragraph: "1",
        reason_short: "Sec 11 — operating expenses incurred in producing business income.",
        confidence_reason: "Sec 11(1) — expenses incurred in the production of income from the business are deductible.",
        legal_confidence: "high",
        source_quote: "11. (1) In calculating a person's income from a business or investment for a year of assessment, expenses to the extent they are incurred during the year by the person and in the production of income from the business or investment, shall be deducted.",
        ui_group: "breakdown",
      },
      {
        component_id: "biz_capital_allowances",
        display_name: "Capital Allowances",
        sort_order: 40,
        default_treatment: "deduct",
        section: "16",
        paragraph: "1",
        reason_short: "Sec 16 — capital allowances / depreciation claimed for the year.",
        confidence_reason: "Sec 16(1) — capital allowances are deducted in calculating income from a business.",
        legal_confidence: "high",
        source_quote: "16. (1) For the purposes of calculating a person's income from a business for a year of assessment — (a) the Capital allowances referred to in subsection (2) shall be deducted; and (b) the balancing allowances referred to in subsection (4) shall be deducted.",
        ui_group: "breakdown",
      },
    ],
  },
  {
    card_id: "investment",
    display_name: "Investment Income",
    sort_order: 20,
    section: "7",
    fields: [
      {
        component_id: "inv_dividends",
        display_name: "Dividends",
        sort_order: 10,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Dividends are included in calculating gains and profits from an investment.",
        confidence_reason: "Directly listed in Section 7(2)(a) as dividends.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_interest",
        display_name: "Interest",
        sort_order: 20,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Interest is included in calculating gains and profits from an investment.",
        confidence_reason: "Directly listed in Section 7(2)(a) as interest.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_discounts",
        display_name: "Discounts",
        sort_order: 30,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Discounts are included in investment income.",
        confidence_reason: "Directly listed in Section 7(2)(a) as discounts.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_charges",
        display_name: "Charges",
        sort_order: 40,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Charges are included in investment income.",
        confidence_reason: "Directly listed in Section 7(2)(a) as charges.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_annuities",
        display_name: "Annuities",
        sort_order: 50,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Annuities are included in calculating gains and profits from an investment.",
        confidence_reason: "Directly listed in Section 7(2)(a) as annuities.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_natural_resource_payments",
        display_name: "Natural Resource Payments",
        sort_order: 60,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Natural resource payments are included in investment income.",
        confidence_reason: "Directly listed in Section 7(2)(a) as natural resource payments.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_rents",
        display_name: "Rents",
        sort_order: 70,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Included Sec 7(2) rents (Fifth Sch 2(c) 25% base). Put final-WHT rents on inv_final_withholding, not also here.",
        confidence_reason: "Directly listed in Section 7(2)(a) as rents.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_premiums",
        display_name: "Premiums",
        sort_order: 80,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Premiums are included in investment income.",
        confidence_reason: "Directly listed in Section 7(2)(a) as premiums.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_royalties",
        display_name: "Royalties",
        sort_order: 90,
        default_treatment: "include",
        section: "7",
        paragraph: "2(a)",
        reason_short: "Royalties are included in calculating gains and profits from an investment.",
        confidence_reason: "Directly listed in Section 7(2)(a) as royalties.",
        legal_confidence: "high",
        source_quote: "dividends, interest, discounts, charges, annuities, natural resource payments, rents, premiums and royalties;",
      },
      {
        component_id: "inv_gains_investment_assets",
        display_name: "Gains from Realisation of Investment Assets",
        sort_order: 100,
        default_treatment: "include",
        section: "7",
        paragraph: "2(b)",
        reason_short: "Gains from realisation of investment assets (as calculated under Chapter IV) are included.",
        confidence_reason: "Section 7(2)(b) includes gains from realisation of investment assets (Chapter IV).",
        legal_confidence: "high",
        source_quote: "gains from the realisation of investment assets as calculated under Chapter IV;",
      },
      {
        component_id: "inv_restriction_consideration",
        display_name: "Restriction Consideration",
        sort_order: 110,
        default_treatment: "include",
        section: "7",
        paragraph: "2(c)",
        reason_short: "Amounts derived as consideration for accepting a restriction on the capacity to conduct the investment are included.",
        confidence_reason: "Directly listed in Section 7(2)(c).",
        legal_confidence: "high",
        source_quote: "amounts derived as consideration for accepting a restriction on the capacity to conduct the investment;",
      },
      {
        component_id: "inv_gifts",
        display_name: "Investment Gifts",
        sort_order: 120,
        default_treatment: "include",
        section: "7",
        paragraph: "2(d)",
        reason_short: "Gifts received in respect of the investment are included.",
        confidence_reason: "Directly listed in Section 7(2)(d) as gifts in respect of the investment.",
        legal_confidence: "high",
        source_quote: "gifts received by the person in respect of the investment;",
      },
      {
        component_id: "inv_winnings",
        display_name: "Lottery / Betting / Gambling Winnings",
        sort_order: 130,
        default_treatment: "include",
        section: "7",
        paragraph: "2(e)",
        reason_short: "Winnings from lotteries, betting or gambling are included in investment income.",
        confidence_reason: "Directly listed in Section 7(2)(e).",
        legal_confidence: "high",
        source_quote: "winnings from lotteries, betting or gambling; and",
      },
      {
        component_id: "inv_other_amounts",
        display_name: "Other Investment Amounts",
        sort_order: 140,
        default_treatment: "include",
        section: "7",
        paragraph: "2(f)",
        reason_short: "Other amounts required to be included under this Act are included in investment income.",
        confidence_reason: "Section 7(2)(f) is a residual include; classifying atypical amounts may need judgment.",
        legal_confidence: "medium",
        source_quote: "other amounts required to be included under this Act.",
      },
      {
        component_id: "inv_final_withholding",
        display_name: "Less: Exempt / Final Withholding Amounts",
        sort_order: 150,
        default_treatment: "final_withholding",
        section: "7",
        paragraph: "3(a)",
        reason_short: "These amounts are excluded from investment income under Sec 7(3)(a) — they are not added to assessable income.",
        confidence_reason: "Section 7(3)(a) excludes exempt amounts and final withholding payments.",
        legal_confidence: "high",
        source_quote: "(3) In calculating a person's gains and profits from an investment for a year of assessment the following shall be excluded:- (a) exempt amounts and final withholding payments;",
      },
    ],
  },
  {
    card_id: "other_income",
    display_name: "Other Income",
    sort_order: 25,
    section: "8",
    fields: [
      {
        component_id: "oth_residual",
        display_name: "Residual other-source gains and profits",
        sort_order: 10,
        default_treatment: "include",
        section: "8",
        paragraph: "1",
        reason_short: "Gains/profits from other sources that are not employment, business, or investment.",
        confidence_reason: "Sec 8 residual head: amounts not already classified under employment (Sec 5), business (Sec 6), or investment (Sec 7). Classification of a specific receipt as 'other' is interpretive; exclude casual and non-recurring profits.",
        legal_confidence: "medium",
        source_quote: "8. (1) A person's income from other sources for a year of assessment shall be that person's gains and profits from any source whatsoever for the year, not including profits of a casual and non-recurring nature.",
        ui_group: "include",
      },
      {
        component_id: "oth_custom",
        display_name: "Custom residual source",
        sort_order: 20,
        default_treatment: "include",
        section: "8",
        paragraph: "1",
        reason_short: "Named residual source under Sec 8 — confirm it is not employment, business, or investment.",
        confidence_reason: "Custom label is user-supplied; treating the amount as Sec 8 residual other income (rather than Sec 5/6/7) requires classification judgment. Not Guide-backed high confidence.",
        legal_confidence: "medium",
        source_quote: "8. (1) A person's income from other sources for a year of assessment shall be that person's gains and profits from any source whatsoever for the year, not including profits of a casual and non-recurring nature.",
        ui_group: "custom",
      },
      {
        component_id: "oth_final_withholding",
        display_name: "Exempt / Final Withholding (Sec 8(2)(a))",
        sort_order: 90,
        default_treatment: "final_withholding",
        section: "8",
        paragraph: "2(a)",
        reason_short: "Excluded from other income under Sec 8(2)(a) — not added to assessable income.",
        confidence_reason: "Section 8(2)(a) directly excludes exempt amounts and final withholding payments from other-source gains.",
        legal_confidence: "high",
        source_quote: "(2) In calculating a person's gains or profits from any source whatsoever, the following shall be excluded:- (a) exempt amounts and final withholding payments; and (b) amounts that are included in calculating the person's income from an employment, business or investment.",
        ui_group: "exclusion",
      },
    ],
  },
];

export function incomeCatalogCard(cardId: string): IncomeCatalogCard | null {
  return INCOME_CATALOG_CARDS.find((card) => card.card_id === cardId) ?? null;
}

export function emptyAmountsForCard(card: IncomeCatalogCard | null): Record<string, string> {
  const next: Record<string, string> = {};
  for (const field of card?.fields ?? []) {
    next[field.component_id] = "0";
  }
  return next;
}

export function includeFieldIds(card: IncomeCatalogCard | null): string[] {
  return (card?.fields ?? [])
    .filter((field) => field.default_treatment === "include")
    .map((field) => field.component_id);
}

export function exclusionFieldIds(card: IncomeCatalogCard | null): string[] {
  return (card?.fields ?? [])
    .filter(
      (field) =>
        field.default_treatment === "final_withholding" ||
        field.default_treatment === "exempt",
    )
    .map((field) => field.component_id);
}

