"""initial schema: transactions, labels, taxability_outputs, review_queue, model_runs

Revision ID: 1368d0abd1f8
Revises: 
Create Date: 2026-04-29 15:44:42.589444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1368d0abd1f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_runs_name_version')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_desc', sa.Text(), nullable=False),
    sa.Column('normalized_desc', sa.Text(), nullable=True),
    sa.Column('amount_lkr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('direction', postgresql.ENUM('CR', 'DR', name='txn_direction'), nullable=False),
    sa.Column('bank_code', sa.String(length=16), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_bank_code_tx_date', 'transactions', ['bank_code', 'tx_date'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_review', 'resolved', 'dismissed', name='review_status'), server_default='pending', nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_queue_status', 'review_queue', ['status'], unique=False)
    op.create_table('taxability_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=False),
    sa.Column('taxability_status', postgresql.ENUM('taxable', 'exempt', 'partially_taxable', 'unknown', name='taxability_status'), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_taxability_outputs_tx_id', 'taxability_outputs', ['tx_id'], unique=False)
    op.create_table('transaction_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=False),
    sa.Column('semantic_category', sa.String(length=64), nullable=False),
    sa.Column('economic_event', sa.String(length=64), nullable=True),
    sa.Column('tax_rule_code', sa.String(length=64), nullable=True),
    sa.Column('label_source', postgresql.ENUM('synthetic', 'weak', 'manual', name='label_source'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_labels_tx_id', 'transaction_labels', ['tx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_labels_tx_id', table_name='transaction_labels')
    op.drop_table('transaction_labels')
    op.drop_index('ix_taxability_outputs_tx_id', table_name='taxability_outputs')
    op.drop_table('taxability_outputs')
    op.drop_index('ix_review_queue_status', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('ix_transactions_bank_code_tx_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('model_runs')
    # Autogenerate does not drop Postgres ENUM types when their owning
    # tables go away; do it explicitly so re-upgrade is idempotent.
    for enum_name in (
        'label_source',
        'taxability_status',
        'review_status',
        'txn_direction',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
