"""add phase1 ingestion tables

Revision ID: 7109b7d4c2a8
Revises: 02c096e1756f
Create Date: 2026-05-05 23:22:13.012644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7109b7d4c2a8'
down_revision: Union[str, None] = '02c096e1756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bank_detected', sa.String(length=32), nullable=True),
    sa.Column('status', postgresql.ENUM('uploaded', 'processing', 'completed', 'failed', name='document_status'), server_default='uploaded', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('text_excerpt', sa.Text(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_no', sa.String(length=128), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_lkr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direction', postgresql.ENUM('CR', 'DR', name='txn_direction', create_type=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_row_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parser_name', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('status', postgresql.ENUM('started', 'completed', 'failed', name='extraction_run_status'), server_default='started', nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_totals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement_totals')
    op.drop_table('extraction_runs')
    op.drop_table('extracted_transactions')
    op.drop_table('document_pages')
    op.drop_table('documents')
    op.execute("DROP TYPE IF EXISTS extraction_run_status")
    op.execute("DROP TYPE IF EXISTS document_status")
    # ### end Alembic commands ###
